name: Generate RSS
run-name: Generating RSS
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 generate_rss.py
      - run: mkdir _site/
      - run: mv rss.xml _site/
      - uses: actions/upload-pages-artifact@v3
